# Generated by Django 5.1.1 on 2024-10-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favoirite_user',
            new_name='favorite_user',
        ),
    ]
